# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


#[[main]]
#  name = "Home"
#  url = "#post"
#  weight = 10

[[main]]
  name = "Math"
  url = "math/"
  weight = 30

[[main]]
  name = "Statistics"
  url = "stats/"
  weight = 40

[[main]]
  name = "Computing"
  url = "cs/"
  weight = 50

 [[main]]
   name = "Notes"
   url = "notes/"
   weight = 60

[[main]]
  name = "About"
  url = "about/"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
#[[main]]
#  name = "Resume"
#  url = "files/cv.pdf/"
#  weight = 70
